# path to apples dataset
data_dir: "data/stavsad"

# out dir and unique name for logging purposes
out_dir: "results_stavsad/"
unique_name: "maskrcnn-adam-1-resnet101-more_anchors_and_maps"

# dataloaders params
batch_size: 1
num_workers: 1

# train params

model_name: "MaskRCNN_resnet101_fpn"
device: "cuda:1"
epochs: 25

scheduler: "MultiStepLR"
milestones:
  - 15
sch_gamma: 0.1
patience: None

# augmentations
augs:
  - "RandomHorizontalFlip"

# optimizer
# momentum=0.9 for SGD by default
optimizer: "Adam"
lr: 0.0001
weight_decay: 0.0001
