# path to apples dataset
data_dir: "data/stavsad"

# out dir and unique name for logging purposes
out_dir: "results_stavsad/"
unique_name: "maskrcnn-base-resnet101"

# dataloaders params
batch_size: 1
num_workers: 1

# train params

model_name: "MaskRCNN_resnet101_fpn"
device: "cuda:1"
epochs: 20

scheduler: "None"
milestones:
  - 20
sch_gamma: 0.1
patience: None

# augmentations
augs:
  - "RandomHorizontalFlip"

# optimizer
# momentum=0.9 for SGD by default
optimizer: "SGD"
lr: 0.001
weight_decay: 0.0001
