# for visualization

model_name: "MaskRCNN_resnet50_fpn"
device: "cuda:0"
weights_path_base: "results_fuji/MaskRCNN_resnet50_fpn/weights/maskrcnn-base.pth"
weights_path_proposed: "results_fuji/MaskRCNN_resnet50_fpn/weights/maskrcnn-adam-5.pth"
data_dir: "data/stavsad"
mode: "all_patches"  # for stavsad only
num_workers: 2

batch_num: 160

confidence_threshold: 0.5

out_dir: "pics/compare/conf0.5/"
grid: True
