# for metrics evaluation

model_name: "MaskRCNN_resnet50_fpn"
device: "cpu"
weights_path: "results_fuji/MaskRCNN_resnet50_fpn/weights/maskrcnn-adam-5.pth"
data_dir: "data/fuji/"
mode: "all_cut_patches"  # only for stavsad dataset
dataframe_path: "evaluation_results/fuji_test.csv"
batch_size: 2
num_workers: 2

